/*
Copyright (C) 2015, 2016 SoLIM Group, University of Wisconsin-Maison, 
Madison, Wisconsin, USA and Institute of Geographic Sciences and Natural 
Resources Research, Chinese Academy of Sciences, Beijing, China

This program is free software: you can redistribute it and/or 
modify it under the terms of the GNU General Public License 
version 3, 2007 as published by the Free Software Foundation.

This program is distributed in the hope that it will be useful, 
but WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
GNU General Public License for more details.

A copy of the GNU General Public License version 3 is provided
 in file GPLv3license.txt. This is also available at: 
 https://www.gnu.org/licenses/gpl-3.0.html.

==================additional conditions============================
If the GNU General Public License conditions do not meet your 
needs to use or incorporate this program (or part of it) into 
other software, SoLIM Solutions may also be available under 
alternative licenses (multi licensing). This allows the program 
to be sold or licensed for use in proprietary applications. In 
this case, please contact any of the members of the SoLIM Group 
listed below to discuss a licensing agreement.
SoLIM Group:
(A-Xing Zhu, Cheng-Zhi Qin, Peng Liang, Fang-He Zhao)
Stat Key Laboratory of Resources and Environmental Information System
Institute of Geographic Sciences and Natural Resources Research,
Chinese Academy of Sciences
11A Datun Road, Chaoyang District, Beijing 100101, PR China
Or 
(A-Xing Zhu)
Department of Geography
University of Wisconsin-Maison
550 N. Park St., Madison, WI 53706, USA
https://solim.geography.wisc.edu/index.htm
Email: dsm_solim@yahoo.com

If you wish to use this program (or part of it), please do credit us
either by citing the proper references in your published papers or in 
your program. Related publications on SoLIM can be found in Appendix 
D: SoLIM Publications in the Appendices of the SoLIM Solutions Help 
system at: http://solim.geography.wisc.edu/software/SoLIMSolutions2013/Help_HTML/index.html. 



By downloading this program, you have agreed to conditions of this license.
*/
//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SoLIM.rc
//
#define IDD_ABOUTBOX                    100
#define IDC_SLIDER                      101
#define IDD_KNOWLEDGE_FORMVIEW          102
#define IDD_INFERENCE_FORMVIEW          103
#define IDR_HTML_3DRVIEWERDLG           104
#define IDC_POINTER_COPY                105
#define IDC_CURSOR_HAND                 105
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_CURVE                133
#define IDD_DIALOG_FREEHAND             133
#define IDD_DIALOG_RANGE                134
#define IDD_DIALOG_WORD                 135
#define IDD_DIALOG_ENUMERATED           136
#define IDD_DIALOG_POINT                137
#define IDD_DIALOG_CURVE1               138
#define IDD_DIALOG_PROJECT_SUMMARY      138
#define IDR_MENU_DATABASE               139
#define IDD_DIALOG_SPATIAL              140
#define IDR_MENU_DATALAYER              140
#define IDR_MENU_SOILTYPE               141
#define IDD_METADATA_FORMVIEW           142
#define IDR_MENU_INSTANCES              142
#define IDR_MENU_OCCURRENCES            143
#define IDD_DIALOG_NORULE               143
#define IDR_MENU_EXCLUSIONS             144
#define IDR_MENU_INSTANCE               145
#define IDR_MENU_OCCURRENCE             146
#define IDD_DIALOG_NEW_PRO              146
#define IDR_MENU_EXCLUSION              147
#define IDD_DIALOG_ADD_LAYER            147
#define IDR_MENU_RULE                   148
#define IDD_DIALOG_SAVEAS               148
#define IDR_MENU_KNOWLEDGEBASE          149
#define IDD_DIALOG_RENAME               153
#define IDD_RidgeLineDlg                154
#define IDD_DIALOG1                     155
#define IDD_BrdNrwRidgeDlg              157
#define IDD_HardenMapDlg                162
#define IDD_CalcStatDlg                 163
#define IDD_OverlayDlg                  164
#define IDC_CURSOR1                     170
#define IDD_RANGE_WIZARD                171
#define IDD_InferenceOptions            173
#define IDD_WIZARD_CURVETYPE            173
#define IDD_WIZARD_RANGE_POINTS         174
#define IDD_WIZARD_POINT_WIDTH          174
#define IDR_KnowledgebaseTypeMnu        177
#define IDD_WIZARD_NAME                 177
#define IDD_WIZARD_RULE_NAME            177
#define IDD_WIZARD_POINT_CENTER         180
#define IDD_WIZARD_RANGE_KEY_POINTS     182
#define IDD_FillShaveDEMDlg             184
#define IDC_CURSOR_CROSS                184
#define IDD_ConvertTacitProjectDlg      186
#define IDB_BITMAP1                     187
#define IDB_LOGO                        187
#define IDD_DIALOG_PURPOSIVE_SAMPLING   189
#define IDD_DIALOG_FCM                  189
#define IDD_DIALOG_PURPOSIVE_SAMPLE     190
#define IDD_CBR_GEN_FILE                191
#define IDD_CBR_SAMPLE                  192
#define IDD_CBR_SEL_DATA                193
#define IDD_CBR_UNCERTAIN               194
#define IDD_KnobDlg                     195
#define IDD_UDADlg                      196
#define IDD_StretchDlg                  197
#define IDD_WetnessDlg                  198
#define IDD_SamplingDlg                 199
#define IDD_HeadwaterDlg                200
#define IDD_FlowDirDlg                  201
#define IDD_FrequencyDlg                202
#define IDD_FilterDlg                   203
#define IDD_CBR_SIMILAR                 204
#define IDD_TerrainPartitionDlg         205
#define IDB_BITMAP_UNCERTAINTY          205
#define IDD_ShoulderDlg                 206
#define IDB_BITMAP_CAL_ATTRI            206
#define IDD_PreviewDlg                  207
#define IDD_3drViewerDlg                207
#define IDD_CBR_TYPE_INFER              208
#define IDD_ColorDlg                    215
#define IDD_PrunBranchDlg               217
#define IDD_BackDlg                     218
#define IDD_CatchmentDlg                219
#define IDD_DerivativeAttrDlg           226
#define ID_FILECONVERTER_3DRGRIDASCII   234
#define IDD_3drTo3dmDlg                 235
#define IDD_FuzzyAspectDlg              238
#define IDD_MFDDlg                      314
#define IDD_CONVERTERDLG                321
#define IDD_3drToAsciiDlg               321
#define IDD_PropertyMapDlg              322
#define IDD_ValueAtSiteDlg              323
#define IDD_ErrorMatrixDlg              324
#define IDD_ErrorMatrixPointListMapDlg  324
#define IDD_ClipDlg                     325
#define IDD_ErrorMatrixWPointsDlg       326
#define IDD_ErrorMatrixPointToPointDlg  326
#define IDD_ReclassDlg                  327
#define IDD_StreamDlg                   328
#define IDD_WIZARD_MINMAX               329
#define IDD_ENUM_WIZARD                 330
#define IDD_CURVE_WIZARD                331
#define IDD_FREEHAND_WIZARD             331
#define IDD_DIALOG_RENAME1              332
#define IDD_DIALOG_ENUM_ITEM            332
#define IDD_WORD_WIZARD                 333
#define IDD_WIZARD_WORD_LIB             334
#define IDC_EDIT_PROJECT_NAME           1000
#define IDC_EDIT_STATIC_PROJECT_NAME    1001
#define IDC_STATIC_PROJECT_NAME         1001
#define IDC_EDIT_PROJECT_DIR            1002
#define IDC_EDIT_SOIL_NUM               1003
#define IDC_STATIC_PROJECT_DIR          1006
#define IDC_BUTTON1                     1007
#define IDC_BTN_BROWSE_MASK             1007
#define IDC_BNT_CHOOSE_MASK             1007
#define IDC_BUTTON_ADD_NODE             1007
#define IDC_BUTTON_ADD_ITEM             1007
#define IDC_BUTTON_CHANGETOCURVERULE    1007
#define IDC_BUTTON_BROWSE               1007
#define IDC_BUTTON_BROWSE_LAYER_FILE    1007
#define IDC_PREV                        1007
#define IDC_BUTTON_UPDATE               1007
#define IDC_BUTTON_3DMAPPER             1007
#define IDC_LookupTableBtn              1007
#define IDC_BUTTON_BROWSE_LAYER_FILE2   1008
#define IDC_STATIC_SOIL_NUM             1009
#define IDC_BUTTON_CHANGETOCURVERULE2   1009
#define IDC_PROJECT_NAME                1010
#define IDC_PROJECT_DIR                 1011
#define IDC_STATIC_LAYER_LIST           1012
#define IDC_SOIL_NUM                    1013
#define IDC_TAB_RULE                    1014
#define IDC_CHECK1                      1015
#define IDC_CHECK_CHECK_FILE            1015
#define IDC_CHECK_USE_SIME              1015
#define IDC_CHECK_USE_SIM               1015
#define IDC_CHECK2                      1016
#define IDC_CHECK_USE_MASK              1016
#define IDC_EDIT1                       1017
#define IDC_EDIT_MASK                   1017
#define IDC_EDIT_LOW_UNITY              1017
#define IDC_EDIT_KNOWLEDGE_BASE_NAME    1017
#define IDC_EDIT_X                      1017
#define IDC_EDIT_NEW_NODE_X             1017
#define IDC_EDIT_ITEM                   1017
#define IDC_EDIT_PRO_NAME               1017
#define IDC_EDIT_LAYER_NAME             1017
#define IDC_EDIT_NAME                   1017
#define IDC_EDIT_LIBFILENAME            1017
#define IDC_EDIT_RULE_NAME              1017
#define IDC_MismatchListFld             1017
#define IDC_EDIT_KENEL                  1017
#define IDC_EDIT2                       1018
#define IDC_EDIT_MASK_VALUE             1018
#define IDC_EDIT_HIGH_UNITY             1018
#define IDC_EDIT_Y                      1018
#define IDC_EDIT_NEW_NODE_Y             1018
#define IDC_EDIT_PRO_DIR                1018
#define IDC_EDIT_LAYER_FILE_PATH        1018
#define IDC_LookupTableFld              1018
#define IDC_EDIT_WEIGHT                 1018
#define IDC_LIST1                       1019
#define IDC_LIST_CHOOSE_SOIL            1019
#define IDC_LIST_METADATA               1019
#define IDC_LIST_CURVENODE              1019
#define IDC_LIST_ITEM                   1019
#define IDC_EDIT_LAYER                  1019
#define IDC_BUTTON_DELETE_NODE          1020
#define IDC_BUTTONREMOVE_ITEM           1020
#define IDC_BUTTON_REMOVE_ITEM          1020
#define IDC_EDIT3                       1021
#define IDC_EDIT_RESULT_DIR             1021
#define IDC_EDIT_LOW_CROSS              1021
#define IDC_EDIT_SEARCH_DIST            1021
#define IDC_EDIT_LAYER2                 1021
#define IDC_EDIT_ITERATION              1021
#define IDC_BUTTON3                     1022
#define IDC_BTN_SET_RESULT_DIR          1022
#define IDC_BTN_RESULT_DIR              1022
#define IDC_BUTTON_MAX_LEFT             1022
#define IDC_BUTTON_REMOVE_LAYER         1022
#define IDC_STATIC_FRAME                1023
#define IDC_BUTTON_RIGHT_RIGHT          1023
#define IDC_BUTTON_MAX_RIGHT            1023
#define IDC_LIST_CLUSTER_NUM            1023
#define IDC_BTN_RUN_INFERENCE           1024
#define IDB_TREE_IMAGE                  1024
#define IDC_BTN_DISPLAY_LAYER           1025
#define IDC_STATIC_LAYER                1026
#define IDC_COMBO_LAYER                 1027
#define IDC_CHECK_USE                   1028
#define IDC_STATIC_SUGGESTION           1029
#define IDC_STATIC_VIEW_RANGE           1030
#define IDC_STATIC_MIN                  1031
#define IDC_STATIC_MAX                  1032
#define IDC_BUT_TEST                    1033
#define IDC_STATIC_MASK_FRAME           1034
#define IDC_STATIC_MASK_VALUE           1035
#define IDC_STATIC_CHOOSE_SOIL          1036
#define IDC_STATIC_MASK_FILE            1036
#define IDC_STATIC_RESULT_DIR           1038
#define IDC_STATIC_CURVE_CANVAS         1039
#define IDC_STATIC_GRAPH_PANEL          1039
#define IDC_EDIT_HIGH_CROSS             1040
#define IDC_STATIC_LOW_UNITY            1041
#define IDC_STATIC_HIGH_UNITY           1042
#define IDC_STATIC_LOW_CROSS            1043
#define IDC_STATIC_HIGH_CROSS           1044
#define IDC_STATIC_LAYER_NUM            1045
#define IDC_EDIT_SOILTYPE_NUM           1046
#define IDC_EDIT_LAYER_NUM              1047
#define IDC_STATIC_KNOWLEDGE_BASE_NAME  1048
#define IDC_STATIC_SOILTYPE_NUM         1049
#define IDC_EDIT_Z_FACTOR               1050
#define IDC_COMBO_INTEGRATED_FUNC       1052
#define IDC_COMBO_X_AXIS_RANGE          1053
#define IDC_COMBO_VIEW_RANGE            1053
#define IDC_COMBO_VIEW_RANGE2           1054
#define IDC_COMBO_CURVE_TYPE            1054
#define IDC_STATIC_CURVE_TYPE           1055
#define IDC_STATIC_RULE_FRAME           1058
#define IDC_COMBO_LIBNAME               1059
#define IDC_COMBO2                      1060
#define IDC_COMBO_CURVENAME             1060
#define IDC_EDIT_CENTRAL_X              1061
#define IDC_EDIT_CENTRAL_Y              1062
#define IDC_EDIT_LEFT_WIDTH             1063
#define IDC_EDIT_RIGHT_WIDTH            1064
#define IDC_STATIC_CENTRAL_X            1065
#define IDC_STATIC_CENTRAL_Y            1066
#define IDC_STATIC_LEFT_WIDTH           1067
#define IDC_STATIC_RIGHT_WIDTH          1068
#define IDC_STATIC_LIBNAME              1069
#define IDC_EDIT4                       1070
#define IDC_EDIT_DIST_DECAY_FACTOR      1070
#define IDC_EDIT_ALPHA                  1070
#define IDC_EDIT_MIN_CLUSTER_NUMBER     1070
#define IDC_STATIC_CURRENTX             1071
#define IDC_STATIC_CURRENTY             1072
#define IDC_FINISH                      1073
#define IDC_CANCEL                      1074
#define IDC_POS                         1075
#define IDC_CHECK_ATTACH_LAYER          1076
#define IDC_EDIT_MAX                    1079
#define IDC_EDIT_MIN                    1080
#define IDC_EDIT_ENUM_ITEM              1085
#define IDC_STATIC_RULE_FOR             1086
#define IDC_STATIC_RULE_TYPE            1087
#define IDC_STATIC_ADD_DELETE           1088
#define IDC_STATIC_DRAG                 1089
#define IDC_STATIC_LOCATION             1090
#define IDC_STATIC_SOIL_TO_INFER        1091
#define IDC_STATIC_INFER_RESULT_FRAME   1092
#define IDC_STATIC_MASK_VALUE_INSTRUCTION 1093
#define IDC_STATIC_X                    1094
#define IDC_STATIC_Y                    1095
#define IDC_BUTTON4                     1096
#define IDC_BUTTON_UPDATE_RULE          1096
#define IDC_BUTTON_IMPORT_DM            1096
#define IDC_BUTTON_CHANGETOFREEHAND     1096
#define IDC_BUTTON_DIR                  1096
#define IDC_OldPrjFileFld               1098
#define IDC_OldProjectFileBtn           1099
#define IDC_OldPrjFileBtn               1099
#define IDC_AccurayReportFld            1100
#define IDC_AccuracyReportLbl           1101
#define IDC_ObservedLbl                 1102
#define IDC_ObservedFld                 1103
#define IDC_LookupTableLbl              1104
#define IDC_ObservedBtn                 1105
#define IDC_PropertyMapLbl              1106
#define IDC_PropertyMapFld              1107
#define IDC_PropertyMapBtn              1108
#define IDC_AccuracyReportFld           1109
#define IDC_AccuracyReportBtn           1110
#define IDC_ValidationNeighborLbl       1111
#define IDC_ValidationNeighborFld       1112
#define IDC_ValidationNodataLbl         1113
#define IDC_ValidationNodataFld         1114
#define IDC_ValidationProBar            1115
#define IDC_EDIT_RESULT_DIRECTORY       1116
#define IDC_LIST_LAYER                  1117
#define IDC_BUTTON_ADD_CLUSTER_NUMBER   1118
#define IDC_BUTTON_REMOVE_CLUSTER_NUMBER 1119
#define IDC_EDIT_CLUSTER_NUM            1120
#define IDC_EDIT_CLUSTER_NUMBER         1121
#define IDC_RADIO_INFER_PROPERTY        1122
#define IDC_RADIO_INFER_PROPERTY2       1123
#define IDC_RADIO_INFER_TYPE            1123
#define IDC_STATIC_NEW_ITEM             1123
#define IDC_LookTBFileBtn               1200
#define IDC_DecayFactorFld              1200
#define IDC_PitDepthFld                 1200
#define IDC_OutFileNameLbl              1201
#define IDC_DecayFactorVLbl             1201
#define IDC_UpperLbl                    1201
#define IDC_OutFileNameFld              1202
#define IDC_DecayFactorVFld             1202
#define IDC_UpperFld                    1202
#define IDC_OutFileNameBtn              1203
#define IDC_LowerLbl                    1203
#define IDC_LowerFld                    1204
#define IDC_FlatAreaLbl                 1205
#define IDC_FlatAreaFld                 1206
#define IDC_SearchDistanceLbl           1207
#define IDC_GradLbl                     1207
#define IDC_SearchDistanceFld           1208
#define IDC_GradFld                     1208
#define IDC_DecayFactorDistLbl          1209
#define IDC_NeighborLbl                 1209
#define IDC_DecayFactorDistFld          1210
#define IDC_NeighborFld                 1210
#define IDC_Parameter1Lbl               1212
#define IDC_DecayFactorHghtFld          1212
#define IDC_PDAlgRdo                    1213
#define IDC_OMAlgRdo                    1214
#define IDC_AlgGrp                      1215
#define IDC_GradAdjustFld               1215
#define IDC_MarkRdo                     1216
#define IDC_SkidmoreAlgRdo              1216
#define IDC_CodingRdo                   1217
#define IDC_ShiAlgRdo                   1217
#define IDC_PreprocessDEMGrp            1218
#define IDC_OrderingRdo                 1218
#define IDC_BrdNrwGrp                   1219
#define IDC_TopoGrp                     1220
#define IDC_Parameter2Lbl               1221
#define IDC_DecayFactorHghtLbl          1221
#define IDC_ContextGrp                  1222
#define IDC_CalcSimParaGrp              1227
#define IDC_PROGRESS1                   1230
#define IDC_EleWidthLbl                 1231
#define IDC_EleWidthFld                 1232
#define IDC_InputDEMLbl                 1233
#define IDC_InputDEMBtn                 1234
#define IDC_InputDEMFld                 1235
#define IDC_FlatAreaGrp                 1236
#define IDC_InputGradientLbl            1236
#define IDC_SettingGrp                  1237
#define IDC_InputGradientFld            1237
#define IDC_InputGradientBtn            1238
#define IDC_FunctionTypeLbl             1245
#define IDC_Width1Lbl                   1246
#define IDC_CaseAlgCmb                  1270
#define IDC_CaseAlgLbl                  1271
#define IDC_VariableGrp                 1272
#define IDC_DistDecayFactorFld          1274
#define IDC_DistDecayFactorLbl          1275
#define IDC_WgtDecayFactorLbl           1276
#define IDC_WgtDecayFactorFld           1277
#define IDC_VtoHConvertFactorLbl        1278
#define IDC_VtoHConvertFactorFld        1279
#define IDC_SpatialSettingGrp           1280
#define IDC_IntegratingAlgoLbl          1281
#define IDC_IntegratingAlgoFld          1282
#define IDC_Width2Lbl                   1284
#define IDC_RbrAlgLbl                   1286
#define IDC_RbrAlgCmb                   1287
#define IDC_LowerValueLbl               1288
#define IDC_LabelFileFld                1290
#define IDC_WorkDirFld                  1291
#define IDC_HSVRdo                      1292
#define IDC_LjgRdo                      1293
#define IDC_OutputPrefixFld             1294
#define IDC_LabelFileLbl                1296
#define IDC_UpperValueLbl               1297
#define IDC_WorkDirLbl                  1297
#define IDC_UpperValue1Fld              1298
#define IDC_OutputPrefixLbl             1298
#define IDC_ColorModelLbl               1299
#define IDC_GammaCorrectionChk          1300
#define IDC_InputFld                    1309
#define IDC_InputLbl                    1310
#define IDC_OutputFld                   1312
#define IDC_SndInputLbl                 1313
#define IDC_FlowDirLbl                  1313
#define IDC_SndInputFld                 1314
#define IDC_FlowDirFld                  1314
#define IDC_FstInputLbl                 1315
#define IDC_FstInputFld                 1316
#define IDC_FstInputBtn                 1317
#define IDC_AlgCmb                      1318
#define IDC_AlgLbl                      1319
#define IDC_OutputLbl                   1321
#define IDC_PreserveIsolatedChk         1323
#define IDC_RemoveSpcValueChk           1324
#define IDC_SpcValueFld                 1325
#define IDC_SpcValueLbl                 1326
#define IDC_CheckFileChk                1327
#define IDC_UseSpatialChk               1329
#define IDC_CheckChk                    1330
#define IDThisRule                      1331
#define IDBatch                         1332
#define IDC_r1Lbl                       1333
#define IDC_r2Lbl                       1334
#define IDC_MaskFileBtn                 1337
#define IDC_MaskChk                     1338
#define IDC_MaskFileFld                 1339
#define IDC_MaskValueFld                1342
#define IDC_MaskValueLbl                1343
#define IDC_OptionGrp                   1344
#define IDC_MoreOptionBtn               1346
#define IDC_SpatialSettingBtn           1347
#define IDC_CurveGrp                    1350
#define IDC_Width1Fld                   1355
#define IDC_r1Fld                       1357
#define IDC_Width2Fld                   1358
#define IDC_r2Fld                       1360
#define IDC_LowerValueFld               1361
#define IDC_UpperValueFld               1362
#define IDC_LoadAttrRuleBtn             1363
#define IDC_SaveAttrRuleBtn             1364
#define IDDoThis                        1365
#define IDDoBatch                       1366
#define IDD_POINT_WIZARD                1366
#define IDC_EditEnvListBtn              1367
#define IDD_GdalTo3dr                   1367
#define IDD_GdalTo3drDlg                1367
#define IDD_GdalTo3dmDlg                1368
#define IDD_ConvertOldProjectDlg        1369
#define IDC_LoadSpatialBtn              1370
#define IDD_ConvertSIEDlg               1370
#define IDC_ApplyToTypeRdo              1371
#define IDC_SaveSpatialBtn              1371
#define IDD_ErrorMatrixPntLabMapDlg     1371
#define IDC_ApplyToAllRdo               1372
#define IDD_ErrorMatrixPointPropertyMapDlg 1372
#define IDD_ValidationPointPropertyMapDlg 1372
#define IDC_RemoveBtn                   1373
#define IDD_DIALOG_CLUSTER_NUMBER       1373
#define IDD_WIZARD_POINT_CENTER1        1374
#define IDD_WIZARD_CHOOSE_LAYER         1374
#define IDC_NewBtn                      1375
#define IDC_XFld                        1378
#define IDC_XLbl                        1379
#define IDC_YLbl                        1380
#define IDC_YFld                        1381
#define IDC_MembershipFld               1392
#define IDC_MembershipLbl               1393
#define IDC_ResampleRtoFld              1394
#define IDC_ResampleRtoLbl              1395
#define IDC_UseDistSimChk               1396
#define IDC_CentralValueForLinePolyLbl  1396
#define IDC_ModeToleranceLbl            1398
#define IDC_ModeToleranceFld            1399
#define IDC_OCallaghanRdo               1401
#define IDC_GradientFileFld             1405
#define IDC_DEMFileLbl                  1406
#define IDC_GradientFileLbl             1407
#define IDC_AttrRuleRdo                 1408
#define IDC_PntCaseRdo                  1409
#define IDC_RstCaseRdo                  1412
#define IDC_LineCaseRdo                 1414
#define IDC_PolyCaseRdo                 1415
#define IDC_IntegratingAlgoCmb          1416
#define IDC_RidgelineFileNameLbl        1425
#define IDC_KnobParaGrp                 1426
#define IDC_EleHighLbl                  1427
#define IDC_EleLowLbl                   1428
#define IDC_EleHighFld                  1429
#define IDC_EleLowFld                   1430
#define IDC_ThreshHighLbl               1431
#define IDC_LowerBoundLbl               1431
#define IDC_OutputMinLbl                1431
#define IDC_TheshLowLbl                 1432
#define IDC_LowerBoundFld               1432
#define IDC_OutputMinFld                1432
#define IDC_ThreshHighFld               1433
#define IDC_UpperBoundLbl               1433
#define IDC_OutputMaxLbl                1433
#define IDC_ThreshLowFld                1434
#define IDC_UpperBoundFld               1434
#define IDC_OutputMaxFld                1434
#define IDC_DEMFileNameLbl              1435
#define IDC_UDAFileNameLbl              1435
#define IDC_InputMinLbl                 1435
#define IDC_UDAFileNameFld              1436
#define IDC_InputMinFld                 1436
#define IDC_UDAFileNameBtn              1437
#define IDC_InputMaxLbl                 1437
#define IDC_RandomRdo                   1438
#define IDC_InputMaxFld                 1438
#define IDC_StratifiedRdo               1439
#define IDC_SystematicRdo               1440
#define IDC_VerticalRangeFld            1441
#define IDC_VerticalRangeLbl            1442
#define IDC_HorizontalRangeFld          1443
#define IDC_HorizontalRangeLbl          1444
#define IDC_RegionalRandomRdo           1445
#define IDC_TotalNoChk                  1448
#define IDC_TotalNoFld                  1449
#define IDC_NoInSubChk                  1450
#define IDC_RangeChk                    1451
#define IDC_RegionLbl                   1452
#define IDC_SampleGrp                   1453
#define IDC_OCallaghanGrp               1454
#define IDC_StratifiedRdo2              1454
#define IDC_SkidmoreUpperFld            1457
#define IDC_SkidmoreUpperLbl            1458
#define IDC_SkidmoreLowerLbl            1459
#define IDC_SkidmoreLowerFld            1460
#define IDC_SkidmoreGrp                 1461
#define IDC_SkidmoreRdo                 1464
#define IDC_PeukerRdo                   1465
#define IDC_FlowAccFileLbl              1466
#define IDC_OrderedStreamFileLbl        1466
#define IDC_UDAFileFld                  1467
#define IDC_StreamFileFld               1467
#define IDC_UDABtn                      1468
#define IDC_StreamFileBtn               1468
#define IDC_PlanformLbl                 1469
#define IDC_PlanformFileFld             1470
#define IDC_PlanformBtn                 1471
#define IDC_FlowAccValueLbl             1472
#define IDC_StreamOrderLbl              1472
#define IDC_UDAValueFld                 1473
#define IDC_StreamOrderFld              1473
#define IDC_FlowDirFileLbl              1474
#define IDC_FlowDirFileFld              1475
#define IDC_FlowDirBtn                  1476
#define IDC_ThresholdLowerLbl           1477
#define IDC_UDAValueUpperFld            1478
#define IDC_ThresholdUpperLbl           1479
#define IDC_AlgorithmLbl                1479
#define IDC_ProfileLbl                  1480
#define IDC_ProfileFileFld              1481
#define IDC_ProfileBtn                  1482
#define IDC_ParameterGrp                1483
#define IDC_PlanforWgtFld               1484
#define IDC_SlopeLbl                    1484
#define IDC_PlanformWgtLbl              1485
#define IDC_FlowAccFileFld              1485
#define IDC_ProfileWgtLbl               1486
#define IDC_FlowAccFileBtn              1486
#define IDC_ProfileWgtFld               1487
#define IDC_SmoothRangeLbl              1488
#define IDC_TopPercentFld               1488
#define IDC_PixelTextLbl                1489
#define IDC_MinAreaFld                  1489
#define IDC_XYMaxRdo                    1490
#define IDC_SlopeFileFld                1490
#define IDC_UpSearchRangeLbl            1490
#define IDC_NoRowColRdo                 1491
#define IDC_InputFileLbl                1491
#define IDC_SlopeFileBtn                1491
#define IDC_OutputFileLbl               1492
#define IDC_SlopeThreshLbl              1492
#define IDC_PixelTextLbl2               1492
#define IDC_InputFileFld                1493
#define IDC_SlopeThreshFld              1493
#define IDC_DownSearchRangeLbl          1493
#define IDC_InputFileBtn                1494
#define IDC_RidgeFileLbl                1494
#define IDC_OutputFileFld               1495
#define IDC_RidgeFileFld                1495
#define IDC_OutputFileBtn               1496
#define IDC_RidgeFileBtn                1496
#define IDC_ParaGrp                     1497
#define IDC_CustomizeChk                1498
#define IDC_curveTypeCmb                1500
#define IDC_RangeSld                    1501
#define IDC_PolygonFileNameLbl          1504
#define IDC_PolygonFileNameFld          1505
#define IDC_PolygonFileNameBtn          1506
#define IDC_NoOfElementsLbl             1507
#define IDC_NoOfElementsFld             1508
#define IDC_StreamlineFileFld           1514
#define IDC_StreamlineFileBtn           1515
#define IDC_CombinePartitionChk         1516
#define IDC_AngleFld                    1517
#define IDC_TerrainPartitionFileLbl     1518
#define IDC_StreamlineFileLbl           1521
#define IDC_TerrainPartitionFileFld     1521
#define IDC_TerrainPartitionFileBtn     1522
#define IDC_TopPcntLbl                  1524
#define IDC_PlanformWgtFld              1525
#define IDC_DismissBtn                  1526
#define IDC_MinAreaLbl                  1526
#define IDC_NumberFileLbl               1529
#define IDC_NumberFileFld               1530
#define IDC_NumberFileBtn               1531
#define IDC_RegionFileLbl               1532
#define IDC_RegionFileFld               1533
#define IDC_RegionFileBtn               1534
#define IDC_ColorFileNameLbl            1534
#define IDC_ColorFileNameFld            1535
#define IDC_ColorFileNameBtn            1536
#define IDC_FilterSizeFld               1537
#define IDC_FilterSizeLbl               1538
#define IDC_MinLengthLbl                1539
#define IDC_NumPixelLbl                 1540
#define IDC_MinLengthFld                1541
#define IDC_BckgrdVLbl                  1542
#define IDC_ThreeDRRdo                  1542
#define IDC_BackgroundVFld              1543
#define IDC_ThreeDMRdo                  1543
#define IDC_TerrainAttrCmb              1543
#define IDC_AlgoCmb                     1544
#define IDC_TerrainAttrLbl              1545
#define IDC_NeighborSizeFld             1546
#define IDC_NeighborShapeCmb            1547
#define IDC_DataUnitCmb                 1551
#define IDC_DataUnitLbl                 1552
#define IDC_GridUnitLbl                 1553
#define IDC_PlanformValueLbl            1553
#define IDC_DataUnitCmb2                1554
#define IDC_GridUnitCmb                 1554
#define IDC_ProfileFileLbl              1555
#define IDC_UDAFileLbl                  1556
#define IDC_JumpNodesRdo                1557
#define IDC_AllNodesRdo                 1558
#define IDC_CodingAlgCmb                1561
#define IDC_CodingAlgLbl                1562
#define IDC_DownBtn                     1564
#define IDC_RightBtn                    1565
#define IDC_LowerLimitFor0Fld           1565
#define IDC_LeftBtn                     1566
#define IDC_LowerFor0Lbl                1566
#define IDC_UpBtn                       1567
#define IDC_UpperFor0Lbl                1567
#define IDC_UpperLimitFor0Fld           1568
#define IDC_LowerFor1Lbl                1569
#define IDC_LowerLimitFor1Fld           1570
#define IDC_UpperFor1Lbl                1571
#define IDC_UpperLimitFor1Fld           1572
#define IDC_RuleTre                     1573
#define IDC_FeatureListCtrl             1574
#define IDC_LayerList                   1576
#define IDC_TFuncLbl                    1578
#define IDC_PFuncLbl                    1578
#define IDC_TFuncCmb                    1579
#define IDC_PFuncCmb                    1579
#define IDC_SptGrp                      1582
#define IDC_AuthorLbl                   1586
#define IDC_EFuncLbl                    1587
#define IDC_FileNameBtn                 1588
#define IDC_SetBtn                      1588
#define IDC_AHPBtn                      1588
#define IDC_BrowseDirBtn                1588
#define IDC_OldDirBtn                   1588
#define IDC_ListFileBtn                 1588
#define IDC_ValueFld                    1589
#define IDC_ValueLbl                    1590
#define IDC_FileNameFld                 1591
#define IDC_FileNameLbl                 1592
#define IDC_FieldNameLbl                1593
#define IDC_COMBO1                      1594
#define IDC_FieldCmb                    1594
#define IDC_ViewTypeCmb                 1594
#define IDC_CntValueLinePolyCmb         1594
#define IDC_COMBO_TERRAIN_ATTRI         1594
#define IDC_KBFld                       1595
#define IDC_UseSpatialFld               1596
#define IDC_RunningTypeLbl              1596
#define IDC_KBFeatureLst                1597
#define IDC_ExistingFileGrp             1600
#define IDC_ExsitingFileRdo             1601
#define IDC_SpecifyExtRdo               1602
#define IDC_3drRdo                      1603
#define IDC_3dmRdo                      1604
#define IDC_WgtList                     1604
#define IDC_FirstFactorLst              1605
#define IDC_SecondFactorLst             1606
#define IDC_Wgt1Rdo                     1607
#define IDC_Wgt2Rdo                     1608
#define IDC_Wgt3Rdo                     1609
#define IDC_Wgt4Rdo                     1610
#define IDC_Wgt6Rdo                     1612
#define IDC_Wgt7Rdo                     1613
#define IDC_Wgt8Rdo                     1614
#define IDC_Wgt9rdo                     1615
#define IDC_Wgt9Rdo                     1615
#define IDC_FirstFactorFld              1619
#define IDC_SecondFactorFld             1620
#define IDC_Wgt5Rdo                     1621
#define IDC_NearestNeighborRdo          1624
#define IDC_RADIO2                      1625
#define IDC_BilinearRdo                 1625
#define IDC_NegativeRdo                 1625
#define IDC_RADIO_PD                    1625
#define IDC_RADIO_fg                    1625
#define IDC_RADIO_CBR                   1625
#define IDC_RADIO_POINT                 1625
#define IDC_ViewTypeLbl                 1629
#define IDC_PositiveRdo                 1630
#define IDC_TopValueFld                 1631
#define IDC_MidValueFld                 1632
#define IDC_ShpFileNameLblFld           1632
#define IDC_FuzzyBndChk                 1633
#define IDC_PromptLbl                   1634
#define IDC_OriginValueFld              1635
#define IDC_InverseChk                  1636
#define IDC_IPADDRESS1                  1637
#define IDC_ABOUTLOGO                   1638
#define IDC_ProjectNameFld              1639
#define IDC_ProjectDirFld               1640
#define IDC_LabelFileNameFld            1640
#define IDC_SoLIMKnowledgeFileFld       1640
#define IDC_SIEKnowledgeFileFld         1640
#define IDC_ProNameFld                  1641
#define IDC_ProDirFld                   1642
#define IDC_LayerNumFld                 1643
#define IDC_KnowledgeTypeFld            1644
#define IDC_EDIT6                       1645
#define IDC_KnowledgeNameFld            1645
#define IDC_NewPrjNameFld               1645
#define IDC_EDIT_EPS                    1645
#define IDC_CloseBtn                    1647
#define IDC_PntFileBtn                  1648
#define IDC_DiffNameFld                 1649
#define IDC_RADIO_md                    1651
#define IDC_EDIT_Prange                 1652
#define IDC_EDIT_UB                     1653
#define IDC_EDIT_P                      1654
#define IDC_RATIO_Quinn                 1655
#define IDC_RADIO_Quinn                 1655
#define IDC_RADIO_Default               1656
#define IDC_ElevThreshholdFld           1657
#define IDC_CurveTypeLable              1659
#define IDC_RADIO1                      1661
#define IDC_RADIO_RBR                   1661
#define IDC_RADIO_ATTRIBUTE             1661
#define IDC_RADIO_RANGE                 1661
#define IDC_OldPrjDirFld                1662
#define IDC_RADIO3                      1662
#define IDC_PntFileNameFld              1663
#define IDC_RADIO4                      1663
#define IDC_CellNameEdit                1664
#define IDC_RADIO5                      1664
#define IDC_RADIO6                      1665
#define IDC_CellNameBtn                 1666
#define IDC_NewPrjDirFld                1667
#define IDC_NewDirBtn                   1668
#define IDC_RADIO_LINE                  1670
#define IDC_RADIO_POLYGON               1671
#define IDC_RADIO_RASTER                1672
#define IDC_SoLIMListFileFld            1673
#define IDC_SIEListFileFld              1673
#define IDC_BUTTON2                     1674
#define IDC_KnowledgeFileBtn            1674
#define IDC_RunInferBtn                 1674
#define IDC_InputDM                     1674
#define IDC_ImportDM                    1674
#define IDC_BUTTON_BROWSE_LIBFILE       1674
#define IDC_NEXT                        1674
#define IDC_BUTTON_MIN_LEFT             1674
#define IDC_BUTTON_ADD_LAYER            1674
#define IDC_SCROLLBAR1                  1675
#define IDC_BUTTON_MIN_RIGHT            1675
#define IDC_PROGRESS_MAIN               1676
#define IDC_STATIC_RUNNING_TYPE         1677
#define IDC_BUTTON_MIN_LEFT2            1678
#define IDC_PROGRESS                    1888
#define IDC_FileHeaderFld               2002
#define IDC_DataFld                     2003
#define IDC_RowFld                      2004
#define IDC_ColFld                      2005
#define IDC_RowLbl                      2008
#define IDC_ColLbl                      2009
#define IDC_PixelFld                    2014
#define IDC_PixelLbl                    2015
#define IDC_DecimalDigitsFld            2016
#define IDC_LAYERADD                    2017
#define IDC_DecimalDigitsLbl            2017
#define IDC_LAYERDEL                    2018
#define IDC_DATALOAD                    2019
#define IDC_DATASAVE                    2020
#define IDC_LoadBtn                     2040
#define IDC_SaveBtn                     2041
#define IDC_LoadBtn2                    2043
#define IDC_AddBtn                      2043
#define IDC_DOINFERBTN                  2056
#define IDC_XminFld                     2061
#define IDC_NoInSubFld                  2061
#define IDC_SmoothRangeFld              2061
#define IDC_REMSLVINFILEBTN             2062
#define IDC_DoInference                 2062
#define IDC_InputFileNameBtn            2062
#define IDC_LabelFileBtn                2062
#define IDC_InputBtn                    2062
#define IDC_ApplyBtn                    2062
#define IDC_UpSearchRangeFld            2062
#define IDC_REMSLVOUTFILEBTN            2063
#define IDC_OutputFileNameBtn           2063
#define IDC_OutputBtn                   2063
#define IDC_XminFld2                    2063
#define IDC_YminFld                     2064
#define IDC_InputRidgelineBtn           2064
#define IDC_SndInputBtn                 2064
#define IDC_DEMFileNameBtn              2064
#define IDC_GradientFileNameBtn         2064
#define IDC_RasterFileNameBtn           2064
#define IDC_DownSearchRangeFld          2064
#define IDC_CASEMATCHINGLBL             2065
#define IDC_XmaxFld                     2065
#define IDC_GradientFileBtn             2065
#define IDC_FlowDirFileBtn              2065
#define IDC_CASEMATCHINGMTHDCMB         2066
#define IDC_YmaxFld                     2066
#define IDC_FACTORMATCHINGMHDLBL        2067
#define IDC_NumOfRowsFld                2067
#define IDC_NumOfColsFld                2068
#define IDC_ExistingFileNameBtn         2069
#define IDC_REMSLVINPUTFILELBL          2077
#define IDC_REMSLVINPUTFILEFLD          2078
#define IDC_REMSLVOUTPUTFILELBL         2079
#define IDC_REMSLVOUTFILEFLD            2080
#define IDC_REMSLVCUTAREALBL            2081
#define IDC_REMSLVCUTAREAFLD            2082
#define IDC_REMSLV4CONNECTRDO           2083
#define IDC_REMSLVNODATALBL             2084
#define IDC_REMSLV8CONNECTRDO           2085
#define IDC_REMSLVISOYESRDO             2086
#define IDC_REMSLVISONORDO              2087
#define IDC_REMSLVNODATAFLD             2088
#define IDC_REMSLVISOLBL                2089
#define IDREMSLVOK                      2090
#define IDREMSLVCANCEL                  2091
#define IDC_CONVERTERINPUTFILELBL       2101
#define IDC_CONVERTERINPUTFILEFLD       2102
#define IDC_CONVERTERINFILEBTN          2103
#define IDC_CONVERTEROUTPUTFILELBL      2104
#define IDC_CONVERTEROUTFILEFLD         2105
#define IDC_CONVERTEROUTFILEBTN         2106
#define IDC_CONVERTERPROGRESS           2107
#define IDCONVERTEROK                   2108
#define IDCONVERTERCANCEL               2109
#define IDC_PropertyMapInFileLbl        2110
#define IDC_PropertyMapInFileBtn        2112
#define IDC_PropertyMapOutFileLbl       2113
#define IDC_PropertyMapOutFileFld       2114
#define IDC_PropertyMapOutFileBtn       2115
#define IDC_PropertyMapProBar           2116
#define IDPropertyMapOK                 2117
#define IDC_ValueAtSiteDataFld          2117
#define IDPropertyMapCancel             2118
#define IDC_ValueAtSiteDataBtn          2118
#define IDC_ValueAtSiteOutFld           2119
#define IDC_WorkingDirFld               2119
#define IDC_ValueAtSiteOutBtn           2120
#define IDC_WorkingDirBtn               2120
#define IDC_ValueAtSiteDataLbl          2121
#define IDC_WorkingDirLbl               2121
#define IDC_ValueAtSiteOutLbl           2122
#define IDC_ValueAtSitePntLbl           2123
#define IDC_ValueAtSitePntFld           2124
#define IDC_ValueAtSitePntBtn           2125
#define IDC_ValueAtSiteProBar           2129
#define IDValueAtSiteOK                 2130
#define IDValueAtSiteCancel             2131
#define IDC_ErrorMatrixPntFileLbl       2139
#define IDC_ErrorMatrixPntFileFld       2140
#define IDC_ErrorMatrixPntFileBtn       2141
#define IDC_ErrorMatrixHardenedMapLbl   2142
#define IDC_ErrorMatrixHardenedMapFld   2143
#define IDC_ErrorMatrixHardenedMapBtn   2144
#define IDC_ErrorMatrixMatrixLbl        2145
#define IDC_ErrorMatrixMatrixFld        2146
#define IDC_ErrorMatrixMatrixBtn        2147
#define IDC_ErrorMatrixProBar           2148
#define IDErrorMatrixOK                 2149
#define IDErrorMatrixCancel             2150
#define IDC_ErrorMatrixSoilListFld      2151
#define IDC_ErrorMatrixSoilListBtn      2152
#define IDC_ErrorMatrixSoilListLbl      2153
#define IDC_ErrorMatrixNeighborLbl      2154
#define IDC_ErrorMatrixNeighborFld      2155
#define IDC_ErrorMatrixNodataLbl        2156
#define IDC_ErrorMatrixNodataFld        2157
#define IDC_ErrorMatrixLblFileFld       2158
#define IDC_ErrorMatrixLabFileFld       2158
#define IDC_ErrorMatrixLblFileBtn       2159
#define IDC_ErrorMatrixLblFileLbl       2160
#define IDC_InputFileNameFld            2176
#define IDC_OutputFileNameFld           2177
#define IDC_InputFileNameLbl            2178
#define IDC_DEMFileNameFld              2178
#define IDC_OutputFileNameLbl           2179
#define IDC_ScissorExtentGbx            2180
#define IDC_ThresholdLbl                2180
#define IDC_LabelLbl                    2180
#define IDC_InputRidgelineLbl           2180
#define IDC_SlopeFileNameLbl            2180
#define IDC_RasterFileNameFld           2180
#define IDC_XminLbl                     2181
#define IDC_ThresholdFld                2181
#define IDC_LabelFld                    2181
#define IDC_InputRidgelineFld           2181
#define IDC_GradientFileNameFld         2181
#define IDC_RasterFileNameLbl           2181
#define IDC_YminLbl                     2182
#define IDC_NeighborhoodLbl             2182
#define IDC_GradientLbl                 2182
#define IDC_InputRidgeLbl               2182
#define IDC_RidgeLabelLbl               2182
#define IDC_XmaxLbl                     2183
#define IDC_NeighborhoodFld             2183
#define IDC_GradientFld                 2183
#define IDC_InputRidgeFld               2183
#define IDC_RidgeLabelFld               2183
#define IDC_YmaxLbl                     2184
#define IDC_CoeffEleLbl                 2184
#define IDC_TPEleDiffFld                2184
#define IDC_NumOfRowsLbl                2185
#define IDC_CoeffEleFld                 2185
#define IDC_TPEleDiffLbl                2185
#define IDC_ScissorOrLbl                2186
#define IDC_CoeffGradLbl                2186
#define IDC_ElevationLbl                2186
#define IDC_NumOfColsLbl                2187
#define IDC_CoeffGradFld                2187
#define IDC_ElevationFld                2187
#define IDC_ProgressBar                 2188
#define IDC_GradWidthLbl                2188
#define IDC_TopProportionFld            2188
#define IDC_1stLblFileLbl               2189
#define IDC_StopValueLbl                2189
#define IDC_ExistingFileNameFld         2189
#define IDC_TopProportionLbl            2189
#define IDC_1stLblFileFld               2190
#define IDC_StopValueFld                2190
#define IDC_AlgoLbl                     2190
#define IDC_HideText                    2190
#define IDC_1stLblFileBtn               2191
#define IDC_CoeffEleLbl2                2191
#define IDC_GradWidthFld                2191
#define IDC_NeighborSizeLbl             2191
#define IDC_2ndLblFileLbl               2192
#define IDC_CoeffEleFld2                2192
#define IDC_EleAdjustLbl                2192
#define IDC_NeighborShapeLbl            2192
#define IDC_InferredLbl                 2192
#define IDC_2ndLblFileFld               2193
#define IDC_CoeffGradLbl2               2193
#define IDC_EleAdjustFld                2193
#define IDC_InferredFld                 2193
#define IDC_2ndLblFileBtn               2194
#define IDC_CoeffGradFld2               2194
#define IDC_GradAdjustLbl               2194
#define IDC_InferredBtn                 2194
#define IDC_NodataFld                   2195
#define IDC_NodataLbl                   2196
#define IDC_SearchDistLbl               2197
#define IDC_PeakHeightLbl               2197
#define IDC_Nodata2Lbl                  2197
#define IDC_LookTBFileLbl               2198
#define IDC_SearchDistFld               2198
#define IDC_PeakHeightFld               2198
#define IDC_NodataFld2                  2198
#define IDC_Nodata2Fld                  2198
#define IDC_LookTBFileFld               2199
#define IDC_DecayFactorLbl              2199
#define IDC_PitDepthLbl                 2199
#define IDC_PropertyMapInFileFld        2211
#define ID_PROJECT_NEW                  32776
#define ID_PROJECT_OPEN                 32777
#define ID_PROJECT_SAVE                 32778
#define ID_PROJECT_SAVE_AS              32779
#define ID_VIEW_DATABASEVIEW            32781
#define ID_VIEW_KNOWLEDGEVIEW           32782
#define ID_VIEW_INFERENCEVIEW           32783
#define ID_HELP_SOLIMHELP               32785
#define ID_VIEW_PROJECT_TREE            32790
#define ID_NAVIGATION_ZOOMIN            32791
#define ID_NAVIGATION_PAN               32792
#define ID_NAVIGATION_ZOOMOUT           32793
#define ID_NAVIGATION_RECT_ZOOM         32794
#define ID_NAVIGATION_ENTIRE_LAYER      32795
#define ID_DATABASE_ADDLAYER            32796
#define ID_DATALAYER_SETSOURCEFILE      32797
#define ID_DATALAYER_DELETE             32798
#define ID_EXCLUSION_ADDRULE            32799
#define ID_EXCLUSIONS_ADDEXCLUSION      32800
#define ID_SOILTYPE_DELETE              32801
#define ID_RULE_DELETE                  32802
#define ID_OCCURRENCES_ADDOCCURRENCE    32803
#define ID_OCCURRENCE_DELETE            32804
#define ID_OCCURRENCE_ADDRULE           32805
#define ID_KNOWLEDGEBASE_ADDSOILTYPE    32806
#define ID_INSTANCES_ADDINSTANCE        32807
#define ID_INSTANCE_DELETE              32808
#define ID_INSTANCE_ADDRULE             32809
#define ID_EXCLUSION_DELETE             32810
#define ID_EXCLUSION_RENAME             32811
#define ID_OCCURRENCE_RENAME            32812
#define ID_SOILTYPE_RENAME              32813
#define ID_RULE_RENAME                  32814
#define ID_INSTANCE_RENAME              32815
#define ID_DATALAYER_RENAME             32817
#define ID_EDIT_ADD                     32818
#define ID_EDIT_DELETE                  32819
#define ID_VALIDATION_ERRORMATRIX_WITHPOINTS 32820
#define ID_EDIT_RENAME                  32821
#define ID_PRODUCTDERIVATION_PROPERTYMAP 32823
#define ID_UTILITIES_CLIP               32824
#define ID_PRODUCTDERIVATION_HARDENFUZZYMAPS 32825
#define ID_DATAPREPARATION_NDVI         32826
#define ID_DATAPREPARATION_DEMFILLANDSHAVE 32827
#define ID_DATAPREPARATION_SURFACEDERIVATIVES 32828
#define ID_DATAPREPARATION_FLOWDIRECTION 32829
#define ID_DATAPREPARATION_SHOULDER     32830
#define ID_DATAPREPARATION_FLOWACCUMULATIONSINGLE 32831
#define ID_DATAPREPARATION_BACK         32832
#define ID_DATAPREPARATION_FLOWACCUMULATIONMULTIPLE 32833
#define ID_DATAPREPARATION_WETNESSINDEX 32834
#define ID_DATAPREPARATION_CACHMENT     32835
#define ID_DATAPREPARATION_TERRAINPARTITION 32836
#define ID_FILECONVERTER_3DR3DM         32840
#define ID_FILECONVERTER_CALCSTATISTICS 32841
#define ID_UTILITIES_REMOVESLIVERS      32842
#define ID_UTILITIES_DIVERSITY          32843
#define ID_UTILITIES_PRUNBRANCHES       32844
#define ID_UTILITIES_RECLASS            32846
#define ID_UTILITIES_STRETCH            32847
#define ID_UTILITIES_OVERLAY            32848
#define ID_UTILITIES_FILTER             32849
#define ID_UTILITIES_FREQUENCY          32850
#define ID_UTILITIES_COLOR              32851
#define ID_UTILITIES_PREPARECASEBASE    32852
#define ID_UTILITIES_3DVISUALIZATION    32854
#define ID_DATAPREPARATION_SIMILAR      32861
#define ID_DATAPREPARATION_RIDGELINE    32862
#define ID_DATAPREPARATION_BROADNARROWRIDGELINE 32863
#define ID_DATAPREPARATION_HEADWATER    32864
#define ID_DATAPREPARATION_STREAMLINE   32865
#define ID_KNOWLEDGEEXTRACTION_DATAMINING 32866
#define ID_FILECONVERTER_GRIDASCII3DR   32868
#define ID_UTILITIES_3DRVIEWER          32869
#define ID_ADDRULE_RANGERULE            32871
#define ID_ADDRULE_WORDRULE             32872
#define ID_ADDRULE_POINTRULE            32873
#define ID_ADDRULE_ENUMERATEDRULE       32874
#define ID_VALIDATION_ERRORMATRIX_WITHMAP 32875
#define ID_HELP_EEEEE                   32898
#define ID_RULE_VIEWATTACHEDLAYER       32899
#define ID_Menu_EXPORT_CLASS            32901
#define ID_DATABASE_DATALOCATION        32902
#define ID_RULE_COPY                    32903
#define ID_OCCURRENCE_PASTE             32904
#define ID_EXCLUSION_PASTE              32905
#define ID_INSTANCE_PASTE               32906
#define ID_PROJECT_RECENTFILES          32907
#define ID_RECENTFILES_1                32908
#define ID_RECENTFILES_2                32909
#define ID_RECENTFILES_3                32910
#define ID_RECENTFILES_4                32911
#define ID_RECENTFILES_CLEARRECENTFILELIST 32912
#define ID_ADDRULE_FREEHANDRULE         32913
#define ID_FILECONVERTER_OTHERRASTERFORMAT 32915
#define ID_FILECONVERTER_OTHERTO3DM     32916
#define ID_PROJECT_CONVERTFROMSOLIM4    32917
#define ID_PROJECT_CONVERTFROMOLDSOLIM  32919
#define ID_PROJECT_CONVERTFROMSIE       32920
#define ID_VALIDATION_TYPEVALIDATAION   32921
#define ID_VALIDATION_PROPERTYVALIDATION 32922
#define ID_TYPEVALIDATAION_POINTLISTVS  32923
#define ID_UTILITIES_VALUESATSAMPLESITES 32924
#define ID_UTILITIES_SAMPLE             32925
#define ID_KNOWLEDGEDERIVATION_PURPOSIVESAMPLING 32926
#define ID_PURPOSIVESAMPLING_FCMCLUSTERING 32927
#define ID_PURPOSIVESAMPLING_SAMPLEDESIGN 32928
#define IDD_CBR_GENERATE_FILE           32930
#define ID_MAPPING_WITH_SAMPLES         32930
#define IDC_COMBO_GRIDSIZE              32931
#define ID_Menu                         32931
#define IDC_PROGRESS_GENERATE           32932
#define IDC_STATIC_STATUS               32933
#define ID_UTILITIES_SAMPLEDESIGN       32933
#define IDC_RADIO_SINGLE_VALUE          32934
#define ID_KNOWLEDGEACQUISITION_FROMEXPERTS 32934
#define IDC_RADIO_KDE                   32935
#define ID_KNOWLEDGEACQUISITION_FROMPURPOSIVESAMPLING 32935
#define IDC_RADIO_SINGLE_VALUE_VEGETATION 32936
#define ID_KNOWLEDGEACQUISITION_FROMMAP 32936
#define IDC_RADIO_KDE_VEGETATION        32937
#define ID_DATAPREPARATION_REMOTESENSING 32937
#define ID_BACK                         32938
#define ID_BUTTON32938                  32938
#define IDD_CBR_DIALOG_SAMPLE_DATA      32939
#define IDC_LIST_Sample                 32940
#define IDC_BUTTON_GET_SAMPLE           32941
#define IDC_BUTTON_CLEAR_SAPMLE_LIST    32942
#define IDC_COMBO_FIELD_Y               32943
#define IDC_COMBO_FIELD_X               32944
#define IDC_LIST_ALL_FIELD              32945
#define IDC_LIST_SEL_FIELD              32946
#define IDC_BUTTON_ADD_FIELD            32947
#define IDC_BUTTON_ADD_FIELD2           32948
#define IDD_CBR_DIALOGSmallScale        32949
#define IDC_BUTTON_ADD_CLIMATE          32950
#define IDC_LIST_CLIMATE                32951
#define IDC_BUTTON_REMOVE_CLIMATE       32952
#define IDC_LIST_PARENTMATERIAL         32953
#define IDC_BUTTON_ADD_PARENTMATERIAL   32954
#define IDC_BUTTON_REMOVE_PARENTMARERIAL 32955
#define IDC_STATIC_PARENTMATERIAL       32956
#define IDC_STATIC_TOPOGRAPHIC          32957
#define IDC_LIST_TOPOGRAPHIC            32958
#define IDC_BUTTON_ADD_TOPOGRAPHIC      32959
#define IDC_BUTTON_REMOVE_TOPOGRAPHIC   32960
#define IDC_STATIC_TOPOGRAPHIC2         32961
#define IDC_LIST_VEGETATION             32962
#define IDC_BUTTON_ADD_VEGETATION       32963
#define IDC_BUTTON_REMOVE_VEGETATION    32964
#define IDD_CBR_Uncertainty             32965
#define IDD_CBR_VALUE_PREDICTION        -32571
#define IDC_EDIT_Uncertaintyfilename    32966
#define IDC_EDIT_Threshold              32967
#define IDC_EDIT_Valuesfoldername       32968
#define IDC_BUTTON_SaveValues           32969
#define IDD_CBR_SIMILARITY              32970
#define IDC_EDIT_CLIMATE_CUT            32971
#define IDC_EDIT_CLIMATE_WEIGHT         32972
#define IDC_COMBO_Climate               32974
#define IDC_COMBO_CASE                  32975
#define IDC_COMBO_TOPOLOGY              32976
#define IDC_COMBO_PM2                   32977
#define IDC_COMBO_VEGETATION            32978
#define IDC_EDIT_VEGETAION_WEIGHT       32979
#define IDC_BUTTON_SaveUncertainty      32980
#define IDC_EDIT_TOPOLOGY_WEIGHT        32981
#define IDC_LIST_ALL_TYPE               32982
#define IDC_BUTTON_ADD_TYPE             32983
#define IDC_BUTTON_ADD_TYPE2            32984
#define IDC_LIST_SEL_TYPE               32985
#define IDC_RADIO_PROPERTY              32986
#define IDC_RADIO_TYPE                  32987
#define IDC_COMBO_TYPE_FIELD            32988
#define IDC_EDIT_MAXIMUM_SIMI           32989
#define IDC_BUTTON_Save_SIM             32990
#define IDC_EDIT_TIMES_FILENAME         32992
#define IDC_EDIT_SIM_THRESHOLD          32993
#define IDC_BUTTON_SAVE_TIMES           32994

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        209
#define _APS_NEXT_COMMAND_VALUE         32939
#define _APS_NEXT_CONTROL_VALUE         1124
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
